-- DROPS THE DATABASE IF IT ALREADY EXISTS --
DROP DATABASE IF EXISTS employee_trackerDB;

-- CREATES DATABASE --
CREATE DATABASE employee_trackerDB;

-- USES DATABASE FOR FOLLOWING STATEMENTS --
USE employee_trackerDB;

-- CREATING DEPARTMENT TABLE --
CREATE TABLE department (
    -- CREATE ID COLUMN --
    id INT NOT NULL AUTO_INCREMENT,
    -- MAKES ID PRIMARY KEY --
    PRIMARY KEY (id),
    -- MAKES NAME COLUMN --
    name VARCHAR(30) NOT NULL;
)
