-- DROPS THE DATABASE IF IT ALREADY EXISTS --
DROP DATABASE IF EXISTS employee_trackerDB;

-- CREATES DATABASE --
CREATE DATABASE employee_trackerDB;

-- USES DATABASE FOR FOLLOWING STATEMENTS --
USE employee_trackerDB;

